@startuml

class Player {
    - name: string
    - hp: int
    - protection: int
    - mana: int
    - abilities: vector<Ability>

    + useAbility()
    + consumeMana()
}

class Ability {
    - name: string
    - manaCost: int
    - coolDownValue: int
    - currentCoolDown: int

    ' canActivate verifica se a habilidade pode ser usada '
    + canActivate()
    + activate()
    ' update atualiza o cooldown para que possa ser usado de novo '
    + updateCoolDown()
}

class Stats {
    - hp: int
    - protection: int
    - mana: int

    + updateStats()
}

Player "1" *-- "*" Ability
Player "1" *-- "*" Stats

@enduml